### ISSUE TITLE
【嘉宾分享】【2020/11/12】Harbor助力玩转云原生，邹佳

### ISSUE THREAD

**Issue by khalke** [cloudnativeto/academy#28]
准备阶段

- [x] 讲师邀请
- [x] 直播档期确认
- [x] 话题及讲师材料收集
- [x] 提问问卷准备
- [x] 分享时演示的demo
- [x] 公众号发布活动信息
- [x] 活动发布活动信息/合作社区转发（CNCF、阿里云云原生、腾讯云云原生）
- [x] 抽奖奖品准备（书籍、社区赞助T恤、极客时间课程）

活动中

- [x] 主播联系讲师开始直播
- [x] 分享主题交流/优化（可选）
- [x] 收集问题 （直播中的提问优化、主持人准备问题、问卷收集问题、邀请嘉宾）（主持人---》志愿，）

活动后

- [x] 直播的时候处理并上传 B 站
- [ ] 讲师的 PPT 归档到云原生学院 repo
- [x] 直播 AMA 的问题整理（深刻的问题，好的问题===》嘉宾check 哪些问题是一个好问题）(问题-->整理好的文字***）（让嘉宾再补一些敏感的问题，常见的问题，新用户常见的问题，FAQ）
 - [x] 直播文字分享稿整理 (讲师提供，没有就不做）
 - [ ] 公众号分享本次直播回顾
 - [x] 抽奖

以上所有事情完成后即可关闭此 issue。

**Comment by Miss-you** [comment]
本周四我们邀请了VMware主任工程师邹佳为大家分享《Harbor 助你玩转云原生》，这个问卷收集大家想向讲师邹佳老师问的关于Harbor的问题
https://wj.qq.com/s2/7504382/d55e
