### ISSUE TITLE
云原生学院第 18 期分享，IstioCon 2021 回顾及开源项目 GetIstio 介绍

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/academy#49]
- 北京时间 2021 年 3 月 4 日下午 12:30 - 2:00
- 主题：IstioCon 2021 回顾及开源项目 GetIstio 介绍
- 直播地址：https://live.bilibili.com/22230973
- 在线文档：https://docs.qq.com/doc/DYVBSVG1pTVlHdVhv
- 主持人：厉辉

## 嘉宾

- 宋净超
- 周礼赞

## 议题

1. IstioCon 2021 回顾
2. Istio 2021 Roadmap
3. Tetrate 开源项目 GetIstio 及 GetEnvoy 介绍
4. Istio 第三轮官网翻译志愿者招募
5. 学习资源分享

**Comment by Miss-you** [comment]
done
